project_id = "xpgoztaraqdvliitkkfv"

[functions.validate-rfq-access]
verify_jwt = false

[functions.submit-negotiation-response]
verify_jwt = false


[functions.validate-live-confirmation-access]
verify_jwt = false

[functions.submit-live-confirmation]
verify_jwt = false

[functions.request-live-datasheet-upload]
verify_jwt = false

[functions.request-rfq-datasheet-upload]
verify_jwt = false

[functions.process-email-outbox]
verify_jwt = false

[functions.invite-user]
verify_jwt = true

[functions.microsoft-graph-webhook]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.create-user-with-password]
verify_jwt = true

[functions.redeem-invitation]
verify_jwt = false

[functions.met-forecast]
verify_jwt = false

[functions.geocode-customer]
verify_jwt = true

