-- Kjørt direkte mot prosjektet 9. september 2026 som versjon 20260909010927 (f3a_matvaretabellen_columns_index_suggest).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til Matvaretabellen-kolonner, indekser og forslagsfunksjon.
