-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908203903 (h2a_label_stale_columns_triggers).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til kolonner og triggere for utdaterte etikettberegninger.
