-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908201756 (f4_agreements_priority_apply).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til leverandøravtaler med prioritet og atomisk lagring.
