-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908204026 (h2b_primary_link_versions_approve_rpc).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til deklarasjonsversjoner og godkjenningsfunksjon.
