-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908210301 (h5a_label_backup_catalog_helpers).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til hjelpefunksjoner og katalog for etikettfelter.
