-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908210846 (h4a_set_price_calc_type_default).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til set_price og standard kalkyletype på varer.
