-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908210428 (h5b_resolve_label_fields_data).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til oppslag av etikettfelter med data.
