-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908200801 (h1a_breadscale_security_rls).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- Sikret Brødskala-funksjonene og strammet RLS på tilhørende tabeller.
