-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908201725 (f5_count_sheets_and_receipt).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til telleark og sporbart varemottak.
