-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908210659 (h5d_datavask_claims_grants).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til datavask-claims og tilhørende rettigheter.
