-- Kjørt direkte mot prosjektet 9. september 2026 som versjon 20260909011118 (e8_realtime_negotiation_tables).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- Slo på realtime for forhandlingstabellene.
