-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908201849 (f2b_legacy_history_recalc_grants).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- Merket gammel prishistorikk og herdet reberegning og rettigheter.
