-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908211059 (h4c_cost_cache_stale_triggers).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til kostbuffer med triggere for utdaterte kalkyler.
