-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908210956 (h4b_product_cost_rewrite).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- Skrev om kostberegningen for varer.
