-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908200957 (h1d_checks_gtin_cake_tenant).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til sjekker for GTIN, kakeoppsett og selskapstilhørighet.
