-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908201359 (h3b_nutrition_triggers_apply_matvaretabellen).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til triggere og funksjon for å hente næring fra Matvaretabellen.
