-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908200853 (h1b_nutrition_views_coverage).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til næringsvisninger og dekningsgrunnlag for råvarer.
