-- Kjørt direkte mot prosjektet 9. september 2026 som versjon 20260909012213 (h6c_indexes_cleanup_unique_active).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- Ryddet indekser og la til unikhet på aktive rader.
