-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908201606 (f2_price_history_linewise).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- Innførte linjebasert prishistorikk for råvarer.
