-- Kjørt direkte mot prosjektet 8. september 2026 som versjon 20260908210029 (f1_rest_ravarer_security).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- Strammet sikkerheten på resterende råvarefunksjoner.
