-- Kjørt direkte mot prosjektet 9. september 2026 som versjon 20260909011009 (f3b_nutrition_coverage_summary_cron).
-- Fullt innhold: Inkaxy/nbos docs/db-migrasjoner/.
-- Markørfil for migrasjonsmotoren – skal ikke kjøres på nytt.
-- La til oppsummering av næringsdekning og cron.
