// Innsjekket kopi av matvaregruppene i Matvaretabellen
// (select distinct food_group_name from matvaretabellen_foods — 77 grupper, 8. sep 2026).
// Listen er komplett og brukes av en test som vokter at CATEGORY_FOOD_GROUPS
// bare peker på grupper som faktisk finnes.

export const MATVARETABELLEN_GROUP_NAMES: readonly string[] = [
  "Alkoholholdige drikkevarer",
  "Andre brødvarer",
  "Andre brødvarer, hjemmebakt",
  "Annen ost",
  "Annet fett",
  "Belgvekster",
  "Brunost",
  "Brus og energidrikke",
  "Bær",
  "Deiger og farser",
  "Dessert og iskrem",
  "Diverse ingredienser",
  "Egg",
  "Ekstra grovt brød",
  "Ferskost",
  "Fet fisk",
  "Fint brød",
  "Fint brød, hjemmebakt",
  "Fiske- og skalldyrsretter",
  "Fiskeinnmat",
  "Fiskeprodukter",
  "Fjørfe",
  "Fløte og rømme",
  "Frokostblanding",
  "Frukt",
  "Frø",
  "Grovt brød",
  "Grovt brød, hjemmebakt",
  "Gryn, ris og pasta",
  "Grønnsaker, rå og tilberedt",
  "Grønnsaksprodukter",
  "Grøt",
  "Gulost",
  "Halvgrovt brød",
  "Innmat",
  "Juice og smoothie",
  "Kaffe og te",
  "Kaker og søt bakst",
  "Kjeks og småkaker",
  "Kjøttprodukter",
  "Kjøttretter",
  "Knekkebrød og flatbrød",
  "Kosttilskudd",
  "Lam",
  "Mager fisk",
  "Majones og påleggsalater",
  "Margarin og smør",
  "Matolje",
  "Mel",
  "Melk",
  "Middagstilbehør",
  "Muggost",
  "Nøtter",
  "Pannekaker og vafler",
  "Pizza og taco",
  "Plantebasert drikke",
  "Poteter, rå og tilberedt",
  "Potetprodukter",
  "Produkter av frukt og bær",
  "Produkter av nøtter og frø",
  "Påsmurt og lunsjretter",
  "Salater",
  "Sjokolade og godteri",
  "Skalldyr",
  "Smelteost",
  "Snacks",
  "Spedbarnsmat",
  "Storfe og kalv",
  "Sukker og honning",
  "Supper og gryteretter",
  "Svin",
  "Søte pålegg",
  "Urter og krydder",
  "Vann og mineralvann",
  "Vegetarprodukter og -retter",
  "Viltkjøtt",
  "Yoghurt",
];
